// Mock data for development without Supabase
import type { Depot, Vehicle, Customer, VehicleType, MockOrder } from "@/lib/types"

export const mockDepots: Depot[] = [
  {
    id: "depot-1",
    name: "İstanbul Depo",
    city: "İstanbul",
    address: "Esenyurt Sanayi Bölgesi, Kıraç Cad. No:45",
    lat: 41.0328,
    lng: 28.6847,
    capacity: 500,
    capacity_pallets: 500,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "depot-2",
    name: "Ankara Depo",
    city: "Ankara",
    address: "Sincan Organize Sanayi Bölgesi, 3. Cadde No:12",
    lat: 39.9334,
    lng: 32.8597,
    capacity: 350,
    capacity_pallets: 350,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "depot-3",
    name: "İzmir Depo",
    city: "İzmir",
    address: "Torbalı Organize Sanayi Bölgesi, A Blok",
    lat: 38.4192,
    lng: 27.1287,
    capacity: 300,
    capacity_pallets: 300,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockVehicleTypes: VehicleType[] = [
  { id: "vt-1", name: "TIR", capacity_pallets: 33, capacity_kg: 24000, fuel_consumption: 35 },
  { id: "vt-2", name: "Kamyon", capacity_pallets: 15, capacity_kg: 12000, fuel_consumption: 22 },
  { id: "vt-3", name: "Kamyonet", capacity_pallets: 6, capacity_kg: 3500, fuel_consumption: 12 },
]

export const mockVehicles: Vehicle[] = [
  // İstanbul Araçları
  {
    id: "v-1",
    plate: "34 ABC 123",
    vehicle_type: "tir",
    capacity_pallet: 33,
    capacity_kg: 24000,
    depot_id: "depot-1",
    status: "available",
    fuel_consumption_per_100km: 35,
    cost_per_km: 15,
    fixed_daily_cost: 2500,
    avg_speed_kmh: 70,
  },
  {
    id: "v-2",
    plate: "34 DEF 456",
    vehicle_type: "tir",
    capacity_pallet: 33,
    capacity_kg: 24000,
    depot_id: "depot-1",
    status: "available",
    fuel_consumption_per_100km: 35,
    cost_per_km: 15,
    fixed_daily_cost: 2500,
    avg_speed_kmh: 70,
  },
  {
    id: "v-3",
    plate: "34 GHI 789",
    vehicle_type: "kamyon",
    capacity_pallet: 15,
    capacity_kg: 12000,
    depot_id: "depot-1",
    status: "available",
    fuel_consumption_per_100km: 22,
    cost_per_km: 10,
    fixed_daily_cost: 1500,
    avg_speed_kmh: 60,
  },
  {
    id: "v-4",
    plate: "34 JKL 012",
    vehicle_type: "kamyon",
    capacity_pallet: 15,
    capacity_kg: 12000,
    depot_id: "depot-1",
    status: "in_use",
    fuel_consumption_per_100km: 22,
    cost_per_km: 10,
    fixed_daily_cost: 1500,
    avg_speed_kmh: 60,
  },
  {
    id: "v-5",
    plate: "34 MNO 345",
    vehicle_type: "kamyonet",
    capacity_pallet: 6,
    capacity_kg: 3500,
    depot_id: "depot-1",
    status: "available",
    fuel_consumption_per_100km: 12,
    cost_per_km: 6,
    fixed_daily_cost: 800,
    avg_speed_kmh: 50,
  },
  // Ankara Araçları
  {
    id: "v-6",
    plate: "06 XYZ 456",
    vehicle_type: "tir",
    capacity_pallet: 33,
    capacity_kg: 24000,
    depot_id: "depot-2",
    status: "available",
    fuel_consumption_per_100km: 35,
    cost_per_km: 15,
    fixed_daily_cost: 2500,
    avg_speed_kmh: 70,
  },
  {
    id: "v-7",
    plate: "06 QRS 789",
    vehicle_type: "kamyon",
    capacity_pallet: 15,
    capacity_kg: 12000,
    depot_id: "depot-2",
    status: "available",
    fuel_consumption_per_100km: 22,
    cost_per_km: 10,
    fixed_daily_cost: 1500,
    avg_speed_kmh: 60,
  },
  {
    id: "v-8",
    plate: "06 TUV 012",
    vehicle_type: "kamyon",
    capacity_pallet: 15,
    capacity_kg: 12000,
    depot_id: "depot-2",
    status: "maintenance",
    fuel_consumption_per_100km: 22,
    cost_per_km: 10,
    fixed_daily_cost: 1500,
    avg_speed_kmh: 60,
  },
  {
    id: "v-9",
    plate: "06 WXY 345",
    vehicle_type: "kamyonet",
    capacity_pallet: 6,
    capacity_kg: 3500,
    depot_id: "depot-2",
    status: "available",
    fuel_consumption_per_100km: 12,
    cost_per_km: 6,
    fixed_daily_cost: 800,
    avg_speed_kmh: 50,
  },
  // İzmir Araçları
  {
    id: "v-10",
    plate: "35 PQR 678",
    vehicle_type: "tir",
    capacity_pallet: 33,
    capacity_kg: 24000,
    depot_id: "depot-3",
    status: "available",
    fuel_consumption_per_100km: 35,
    cost_per_km: 15,
    fixed_daily_cost: 2500,
    avg_speed_kmh: 70,
  },
  {
    id: "v-11",
    plate: "35 STU 901",
    vehicle_type: "kamyon",
    capacity_pallet: 15,
    capacity_kg: 12000,
    depot_id: "depot-3",
    status: "available",
    fuel_consumption_per_100km: 22,
    cost_per_km: 10,
    fixed_daily_cost: 1500,
    avg_speed_kmh: 60,
  },
  {
    id: "v-12",
    plate: "35 VWX 234",
    vehicle_type: "kamyonet",
    capacity_pallet: 6,
    capacity_kg: 3500,
    depot_id: "depot-3",
    status: "in_use",
    fuel_consumption_per_100km: 12,
    cost_per_km: 6,
    fixed_daily_cost: 800,
    avg_speed_kmh: 50,
  },
]

export const mockCustomers: Customer[] = [
  // İstanbul Müşterileri
  {
    id: "c-1",
    name: "ABC Lojistik",
    address: "Kadıköy, Bağdat Cad. No:123",
    city: "İstanbul",
    lat: 40.9901,
    lng: 29.029,
    demand_pallet: 5,
    demand_pallets: 5,
    demand_kg: 2500,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-1",
  },
  {
    id: "c-2",
    name: "XYZ Market",
    address: "Beşiktaş, Barbaros Bulvarı No:45",
    city: "İstanbul",
    lat: 41.0422,
    lng: 29.0056,
    demand_pallet: 8,
    demand_pallets: 8,
    demand_kg: 4000,
    priority: 5,
    status: "pending",
    assigned_depot_id: "depot-1",
  },
  {
    id: "c-3",
    name: "Mega Depo",
    address: "Ümraniye, Alemdağ Cad. No:78",
    city: "İstanbul",
    lat: 41.0167,
    lng: 29.1167,
    demand_pallet: 12,
    demand_pallets: 12,
    demand_kg: 6000,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-1",
  },
  {
    id: "c-4",
    name: "Süper Gıda",
    address: "Bakırköy, İstanbul Cad. No:56",
    city: "İstanbul",
    lat: 40.9833,
    lng: 28.8667,
    demand_pallet: 6,
    demand_pallets: 6,
    demand_kg: 3000,
    priority: 2,
    status: "active",
    assigned_depot_id: "depot-1",
  },
  {
    id: "c-5",
    name: "Toptan Dağıtım",
    address: "Şişli, Halaskargazi Cad. No:234",
    city: "İstanbul",
    lat: 41.0608,
    lng: 28.9872,
    demand_pallet: 15,
    demand_pallets: 15,
    demand_kg: 7500,
    priority: 5,
    status: "pending",
    assigned_depot_id: "depot-1",
  },
  {
    id: "c-6",
    name: "Anadolu Market",
    address: "Maltepe, Bağlarbaşı Cad. No:12",
    city: "İstanbul",
    lat: 40.9357,
    lng: 29.1306,
    demand_pallet: 4,
    demand_pallets: 4,
    demand_kg: 2000,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-1",
  },
  {
    id: "c-7",
    name: "Marmara Ticaret",
    address: "Sarıyer, Büyükdere Cad. No:89",
    city: "İstanbul",
    lat: 41.1667,
    lng: 29.05,
    demand_pallet: 10,
    demand_pallets: 10,
    demand_kg: 5000,
    priority: 3,
    status: "active",
    assigned_depot_id: "depot-1",
  },
  // Ankara Müşterileri
  {
    id: "c-8",
    name: "Başkent Depo",
    address: "Çankaya, Tunus Cad. No:67",
    city: "Ankara",
    lat: 39.9208,
    lng: 32.8541,
    demand_pallet: 8,
    demand_pallets: 8,
    demand_kg: 4000,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-2",
  },
  {
    id: "c-9",
    name: "Merkez Gıda",
    address: "Keçiören, Fatih Sultan Mehmet Blv. No:123",
    city: "Ankara",
    lat: 39.9975,
    lng: 32.8628,
    demand_pallet: 5,
    demand_pallets: 5,
    demand_kg: 2500,
    priority: 5,
    status: "pending",
    assigned_depot_id: "depot-2",
  },
  {
    id: "c-10",
    name: "Ankara Ticaret",
    address: "Yenimahalle, Mevlana Blv. No:45",
    city: "Ankara",
    lat: 39.9667,
    lng: 32.75,
    demand_pallet: 11,
    demand_pallets: 11,
    demand_kg: 5500,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-2",
  },
  {
    id: "c-11",
    name: "Konya Yolu Market",
    address: "Çankaya, Konya Yolu No:234",
    city: "Ankara",
    lat: 39.8833,
    lng: 32.8167,
    demand_pallet: 7,
    demand_pallets: 7,
    demand_kg: 3500,
    priority: 2,
    status: "active",
    assigned_depot_id: "depot-2",
  },
  // İzmir Müşterileri
  {
    id: "c-12",
    name: "Ege Lojistik",
    address: "Konak, Alsancak Mah. No:56",
    city: "İzmir",
    lat: 38.4333,
    lng: 27.1333,
    demand_pallet: 9,
    demand_pallets: 9,
    demand_kg: 4500,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-3",
  },
  {
    id: "c-13",
    name: "Bornova Depo",
    address: "Bornova, Kazım Dirik Mah. No:78",
    city: "İzmir",
    lat: 38.4667,
    lng: 27.2167,
    demand_pallet: 6,
    demand_pallets: 6,
    demand_kg: 3000,
    priority: 5,
    status: "pending",
    assigned_depot_id: "depot-3",
  },
  {
    id: "c-14",
    name: "Karşıyaka Market",
    address: "Karşıyaka, Cemal Gürsel Cad. No:34",
    city: "İzmir",
    lat: 38.4559,
    lng: 27.1094,
    demand_pallet: 4,
    demand_pallets: 4,
    demand_kg: 2000,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-3",
  },
  {
    id: "c-15",
    name: "Gaziemir Ticaret",
    address: "Gaziemir, Akçay Cad. No:90",
    city: "İzmir",
    lat: 38.3167,
    lng: 27.1333,
    demand_pallet: 13,
    demand_pallets: 13,
    demand_kg: 6500,
    priority: 3,
    status: "pending",
    assigned_depot_id: "depot-3",
  },
]

export interface MockRoute {
  id: string
  vehicle_id: string
  depot_id: string
  total_distance_km: number
  total_duration_min: number
  total_cost: number
  fuel_cost: number
  fixed_cost: number
  status: string
  optimized_at: string
  stops: { customer_id: string; customer_name: string; order: number; arrival_time: string }[]
}

export const mockRoutes: MockRoute[] = [
  {
    id: "route-1",
    vehicle_id: "v-4",
    depot_id: "depot-1",
    total_distance_km: 87.5,
    total_duration_min: 145,
    total_cost: 2850,
    fuel_cost: 1350,
    fixed_cost: 1500,
    status: "in_progress",
    optimized_at: new Date().toISOString(),
    stops: [
      { customer_id: "c-1", customer_name: "ABC Lojistik", order: 1, arrival_time: "09:30" },
      { customer_id: "c-2", customer_name: "XYZ Market", order: 2, arrival_time: "10:45" },
      { customer_id: "c-3", customer_name: "Mega Depo", order: 3, arrival_time: "12:00" },
    ],
  },
  {
    id: "route-2",
    vehicle_id: "v-12",
    depot_id: "depot-3",
    total_distance_km: 45.2,
    total_duration_min: 95,
    total_cost: 1280,
    fuel_cost: 480,
    fixed_cost: 800,
    status: "in_progress",
    optimized_at: new Date().toISOString(),
    stops: [
      { customer_id: "c-12", customer_name: "Ege Lojistik", order: 1, arrival_time: "08:45" },
      { customer_id: "c-13", customer_name: "Bornova Depo", order: 2, arrival_time: "09:30" },
    ],
  },
]

export const mockOrders: MockOrder[] = [
  {
    id: "order-1",
    customer_id: "c-1",
    customer_name: "ABC Lojistik",
    customer_address: "Kadıköy, Bağdat Cad. No:123",
    customer_city: "İstanbul",
    demand_kg: 2500,
    demand_pallet: 5,
    priority: 3,
    status: "pending",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
  {
    id: "order-2",
    customer_id: "c-2",
    customer_name: "XYZ Market",
    customer_address: "Beşiktaş, Barbaros Bulvarı No:45",
    customer_city: "İstanbul",
    demand_kg: 4000,
    demand_pallet: 8,
    priority: 5,
    status: "pending",
    notes: "Acil teslimat",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
  {
    id: "order-3",
    customer_id: "c-3",
    customer_name: "Mega Depo",
    customer_address: "Ümraniye, Alemdağ Cad. No:78",
    customer_city: "İstanbul",
    demand_kg: 6000,
    demand_pallet: 12,
    priority: 3,
    status: "assigned",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
  {
    id: "order-4",
    customer_id: "c-5",
    customer_name: "Toptan Dağıtım",
    customer_address: "Şişli, Halaskargazi Cad. No:234",
    customer_city: "İstanbul",
    demand_kg: 7500,
    demand_pallet: 15,
    priority: 5,
    status: "in_transit",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
  {
    id: "order-5",
    customer_id: "c-8",
    customer_name: "Başkent Depo",
    customer_address: "Çankaya, Tunus Cad. No:67",
    customer_city: "Ankara",
    demand_kg: 4000,
    demand_pallet: 8,
    priority: 3,
    status: "pending",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
  {
    id: "order-6",
    customer_id: "c-9",
    customer_name: "Merkez Gıda",
    customer_address: "Keçiören, Fatih Sultan Mehmet Blv. No:123",
    customer_city: "Ankara",
    demand_kg: 2500,
    demand_pallet: 5,
    priority: 5,
    status: "pending",
    notes: "Randevulu teslimat",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
  {
    id: "order-7",
    customer_id: "c-12",
    customer_name: "Ege Lojistik",
    customer_address: "Konak, Alsancak Mah. No:56",
    customer_city: "İzmir",
    demand_kg: 4500,
    demand_pallet: 9,
    priority: 3,
    status: "delivered",
    delivery_date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "order-8",
    customer_id: "c-13",
    customer_name: "Bornova Depo",
    customer_address: "Bornova, Kazım Dirik Mah. No:78",
    customer_city: "İzmir",
    demand_kg: 3000,
    demand_pallet: 6,
    priority: 5,
    status: "pending",
    delivery_date: new Date().toISOString().split("T")[0],
    created_at: new Date().toISOString(),
  },
]

export function getMockStats() {
  const availableVehicles = mockVehicles.filter((v) => v.status === "available").length
  const pendingCustomers = mockCustomers.filter((c) => c.status === "pending").length
  const pendingOrders = mockOrders.filter((o) => o.status === "pending").length
  const totalDistance = mockRoutes.reduce((sum, r) => sum + r.total_distance_km, 0)
  const totalCost = mockRoutes.reduce((sum, r) => sum + r.total_cost, 0)
  const totalPallets = mockCustomers.reduce((sum, c) => sum + (c.demand_pallet || 0), 0)

  return {
    totalDepots: mockDepots.length,
    totalVehicles: mockVehicles.length,
    availableVehicles,
    totalCustomers: mockCustomers.length,
    pendingCustomers,
    totalOrders: mockOrders.length,
    pendingOrders,
    totalRoutes: mockRoutes.length,
    todayRoutes: mockRoutes.filter((r) => r.status === "in_progress").length,
    totalDistance,
    totalCost,
    totalPallets,
  }
}
